"""Oracle tests for Gate F Release Certification (C09-05)."""

import json
import os
import shutil
import sys
import tempfile

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))
from source.release.gate_f_verifier import GateFVerifier


def test_gate_f_full_system_verification():
    """Execute GateFVerifier.verify_gate_f(); assert status is GATE_F_PASS."""
    verifier = GateFVerifier(project_root=".")
    result = verifier.verify_gate_f(output_path="project/gate_f_report.json")
    assert result["gate_f_status"] == "GATE_F_PASS", (
        f"Gate F failed. Sections: {json.dumps(result['sections'], indent=2)}"
    )
    assert result["all_sections_passed"] is True


def test_gate_f_report_json_exists():
    """Verify project/gate_f_report.json is generated and valid."""
    # Ensure the report was generated by a prior test or generate it now
    if not os.path.exists("project/gate_f_report.json"):
        verifier = GateFVerifier(project_root=".")
        verifier.verify_gate_f()

    assert os.path.exists("project/gate_f_report.json")
    with open("project/gate_f_report.json") as f:
        report = json.load(f)
    assert "gate_f_status" in report
    assert report["gate_f_status"] == "GATE_F_PASS"


def test_gate_f_detects_broken_gate_chain():
    """Test that missing upstream gate report triggers GATE_F_FAIL."""
    tmpdir = tempfile.mkdtemp()
    try:
        # Create a minimal project structure with one gate report missing
        os.makedirs(os.path.join(tmpdir, "project"), exist_ok=True)
        os.makedirs(os.path.join(tmpdir, "results"), exist_ok=True)
        os.makedirs(os.path.join(tmpdir, "paper", "figures"), exist_ok=True)
        os.makedirs(os.path.join(tmpdir, "release"), exist_ok=True)
        os.makedirs(os.path.join(tmpdir, "factory"), exist_ok=True)
        os.makedirs(os.path.join(tmpdir, "source", "topology"), exist_ok=True)
        os.makedirs(os.path.join(tmpdir, "source", "ph"), exist_ok=True)
        os.makedirs(os.path.join(tmpdir, "source", "training"), exist_ok=True)

        # Copy gate reports except gate_b
        for gate in ["gate_c_report.json", "gate_d_report.json", "gate_e_report.json"]:
            shutil.copy(f"project/{gate}", os.path.join(tmpdir, "project", gate))

        # Create stub files for invariant checks
        for stub in [
            "results/confirmatory_stats.json",
            "source/topology/cycle_cell_view.py",
            "source/topology/clique_simplicial_view.py",
            "source/topology/incidence.py",
            "source/ph/persistence_extractor.py",
            "source/training/trainer.py",
            "factory/VERSION",
            "paper/main.tex",
            "paper/references.bib",
            "release/README.md",
        ]:
            filepath = os.path.join(tmpdir, stub)
            os.makedirs(os.path.dirname(filepath), exist_ok=True)
            with open(filepath, "w") as f:
                if stub == "results/confirmatory_stats.json":
                    json.dump({"metadata": {"test_split_sha256": "a" * 64}}, f)
                else:
                    f.write("stub")

        # Create figure stubs
        for fig in ["persistence_diagram.png", "pr_curves.png",
                     "cycle_sensitivity.png", "scalability.png"]:
            with open(os.path.join(tmpdir, "paper", "figures", fig), "w") as f:
                f.write("stub")

        verifier = GateFVerifier(project_root=tmpdir)
        result = verifier.verify_gate_f(
            output_path="project/gate_f_report.json"
        )

        assert result["gate_f_status"] == "GATE_F_FAIL", (
            "Gate F should fail when gate_b_report.json is missing"
        )
        assert result["sections"]["gate_chain"]["passed"] is False
    finally:
        shutil.rmtree(tmpdir)
